export const NAME = 'consent';

export const FETCH_CONSENT_ITEMS = `${NAME}/FETCH_CONSENT_ITEMS`;
export type FETCH_CONSENT_ITEMS = typeof FETCH_CONSENT_ITEMS;

export const FETCH_CONSENT_ITEMS_SUCCESS = `${NAME}/FETCH_CONSENT_ITEMS_SUCCESS`;
export type FETCH_CONSENT_ITEMS_SUCCESS = typeof FETCH_CONSENT_ITEMS_SUCCESS;

export const FETCH_CONSENT_ITEMS_FAIL = `${NAME}/FETCH_CONSENT_ITEMS_FAIL`;
export type FETCH_CONSENT_ITEMS_FAIL = typeof FETCH_CONSENT_ITEMS_FAIL;
