
// Fetch consent items

export const FETCH_CONSENT_ITEMS = 'FETCH_CONSENT_ITEMS';
export type FETCH_CONSENT_ITEMS = typeof FETCH_CONSENT_ITEMS;

export const FETCH_CONSENT_ITEMS_SUCCESS = 'FETCH_CONSENT_ITEMS_SUCCESS';
export type FETCH_CONSENT_ITEMS_SUCCESS = typeof FETCH_CONSENT_ITEMS_SUCCESS;

export const FETCH_CONSENT_ITEMS_FAIL = 'FETCH_CONSENT_ITEMS_FAIL';
export type FETCH_CONSENT_ITEMS_FAIL = typeof FETCH_CONSENT_ITEMS_FAIL;

// Change form values

export const CHANGE_CONSENT_NAME = 'CHANGE_CONSENT_NAME';
export type CHANGE_CONSENT_NAME = typeof CHANGE_CONSENT_NAME;

export const CHANGE_CONSENT_EMAIL = 'CHANGE_CONSENT_EMAIL';
export type CHANGE_CONSENT_EMAIL = typeof CHANGE_CONSENT_EMAIL;

export const ADD_CONSENT_OPTION = 'ADD_CONSENT_OPTION';
export type ADD_CONSENT_OPTION = typeof ADD_CONSENT_OPTION;

export const REMOVE_CONSENT_OPTION = 'REMOVE_CONSENT_OPTION';
export type REMOVE_CONSENT_OPTION = typeof REMOVE_CONSENT_OPTION;

// Fetch consent list

export const FETCH_CONSENT_LIST = 'FETCH_CONSENT_LIST';
export type FETCH_CONSENT_LIST = typeof FETCH_CONSENT_LIST;

export const FETCH_CONSENT_LIST_SUCCESS = 'FETCH_CONSENT_LIST_SUCCESS';
export type FETCH_CONSENT_LIST_SUCCESS = typeof FETCH_CONSENT_LIST_SUCCESS;

export const FETCH_CONSENT_LIST_FAIL = 'FETCH_CONSENT_LIST_FAIL';
export type FETCH_CONSENT_LIST_FAIL = typeof FETCH_CONSENT_LIST_FAIL;

// Create consent

export const CREATE_CONSENT = 'CREATE_CONSENT';
export type CREATE_CONSENT = typeof CREATE_CONSENT;

export const CREATE_CONSENT_SUCCESS = 'CREATE_CONSENT_SUCCESS';
export type CREATE_CONSENT_SUCCESS = typeof CREATE_CONSENT_SUCCESS;

export const CREATE_CONSENT_FAILED = 'CREATE_CONSENT_FAILED';
export type CREATE_CONSENT_FAILED = typeof CREATE_CONSENT_FAILED;
